/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logistics;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Debanjan
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OrderId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Home");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Order Id");

        OrderId.setBackground(new java.awt.Color(255, 204, 204));
        OrderId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(102, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        homebtn.setBackground(new java.awt.Color(255, 0, 0));
        homebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        homebtn.setText("HOME");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(homebtn))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                    .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/location", "root", "");
            String id = OrderId.getText();
            id = encode(id);
            ResultSet rs=conn.createStatement().executeQuery("select * from loc where orderid = '"+id+"' order by date desc");
            ResultSet m = conn.createStatement().executeQuery("select *,COUNT(*) as rowcount from loc where orderid = '"+id+"'");
            m.next();
            int num = m.getInt("rowcount");
            String data[][] = new String[num][2];
            JFrame f=new JFrame();
            int d = 0;
            while(rs.next()){
                data[d][0] = decode(rs.getString(2));
                data[d][1] = decode(rs.getString(3));
                d++;
            }
            String column[]={"OrderId","Location"};
            JTable jt=new JTable(data,column);
            jt.setBounds(30,40,200,300);
            JScrollPane sp=new JScrollPane(jt);
            f.add(sp);
            f.setSize(300,400);
            f.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public static String encode(String str){
        String Newstr = "";
        for (int i=0;i<str.length();i++)  
        {  
            char ch=Character.toLowerCase(str.charAt(i));  
            Newstr = switch (ch) {
                case 'a' -> Newstr+"{";
                case 'b' -> Newstr+"}";
                case 'c' -> Newstr+"#";
                case 'd' -> Newstr+"~";
                case 'e' -> Newstr+"+";
                case 'f' -> Newstr+"-";
                case 'g' -> Newstr+"*";
                case 'h' -> Newstr+"@";
                case 'i' -> Newstr+"/";
                case 'j' -> Newstr+"\\";
                case 'k' -> Newstr+"?";
                case 'l' -> Newstr+"$";
                case 'm' -> Newstr+"!";
                case 'n' -> Newstr+"^";
                case 'o' -> Newstr+"(";
                case 'p' -> Newstr+")";
                case 'q' -> Newstr+"<";
                case 'r' -> Newstr+">";
                case 's' -> Newstr+"=";
                case 't' -> Newstr+";";
                case 'u' -> Newstr+",";
                case 'v' -> Newstr+"_";
                case 'w' -> Newstr+"[";
                case 'x' -> Newstr+"]";
                case 'y' -> Newstr+":";
                case 'z' -> Newstr+"\"";
                case ' ' -> Newstr+" ";
                case '.' -> Newstr+'3';
                case ',' -> Newstr+"1";
                case '(' -> Newstr+'4';
                case '\"' -> Newstr+'5';
                case ')' -> Newstr+"7";
                case '?' -> Newstr+"2";
                case '!' -> Newstr+"8";
                case '-' -> Newstr+"6";
                case '%' -> Newstr+"9";
                case '1' -> Newstr+"r";
                case '2' -> Newstr+"k";
                case '3' -> Newstr+"b";
                case '4' -> Newstr+"e";
                case '5' -> Newstr+"q";
                case '6' -> Newstr+"h";
                case '7' -> Newstr+"u";
                case '8' -> Newstr+"y";
                case '9' -> Newstr+"w";
                case '0' -> Newstr+"z";
                default -> Newstr+"0";
            };  
        }
        return (Newstr);
    }
    public static String decode(String str){
        String Newstr = "";
        for (int i=0;i<str.length();i++)  
        {  
            char ch=Character.toLowerCase(str.charAt(i));  
                Newstr = switch (ch) {
                case '{' -> Newstr+"A";
                case '}' -> Newstr+"B";
                case '#' -> Newstr+"C";
                case '~' -> Newstr+"D";
                case '+' -> Newstr+"E";
                case '-' -> Newstr+"F";
                case '*' -> Newstr+"G";
                case '@' -> Newstr+"H";
                case '/' -> Newstr+"I";
                case '\\' -> Newstr+"J";
                case '?' -> Newstr+"K";
                case '$' -> Newstr+"L";
                case '!' -> Newstr+"M";
                case '^' -> Newstr+"N";
                case '(' -> Newstr+"O";
                case ')' -> Newstr+"P";
                case '<' -> Newstr+"Q";
                case '>' -> Newstr+"R";
                case '=' -> Newstr+"S";
                case ';' -> Newstr+"T";
                case ',' -> Newstr+"U";
                case '_' -> Newstr+"V";
                case '[' -> Newstr+"W";
                case ']' -> Newstr+"X";
                case ':' -> Newstr+"Y";
                case '\"' -> Newstr+"Z";
                case '1' -> Newstr+"r";
                case '2' -> Newstr+"k";
                case '3' -> Newstr+"b";
                case '4' -> Newstr+"e";
                case '5' -> Newstr+"q";
                case '6' -> Newstr+"h";
                case '7' -> Newstr+"u";
                case '8' -> Newstr+"y";
                case '9' -> Newstr+"w";
                case '0' -> Newstr+"z";
                default -> Newstr+"0";
            };  
        }
        return (Newstr);
    }
    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        new Home().setVisible(true);
    }//GEN-LAST:event_homebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OrderId;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
